### ISSUE TITLE
Issue randomly selecting 500 reads in 002 replicate files

### ISSUE THREAD

**Issue by Nicholas-Bartelo** [Theo-Nelson/SMS-colab#1]
Hi Everyone,

I was able to successfully take 500 reads from the 004 file using the following code:

`! slow5tools view HCV_IVT_004_ALIGNED_SIGNALS.blow5 | grep -v '^[#@]' | shuf | head -n 500 | cut -f1 | slow5tools get HCV_IVT_004_ALIGNED_SIGNALS.blow5  -o /content/drive/MyDrive/Single\ Molecular\ Sequencing/HW\ 3/randomly_split_slow5/HCV_IVT_004_ALIGNED_SIGNALS_subset1.slow5 `

However, when I run the same things with the other 002 files, the output is nothing! I did some troubleshooting and found that everything after the "shuf" command is a blank output. 

Can anyone help me understand why this may be happening? I don't understand why this would work for one of the files but not the others. They all pass the quickcheck command test.

Thanks in advance!

**Comment by Nicholas-Bartelo** [comment]
It decided to work today! Same command works for all three samples. I am not sure what happened yesterday. 

This is another way to find 500 random reads which takes longer than the original posted code:
`! slow5tools view HCV_IVT_002_REP1_ALIGNED_SIGNALS.blow5 | awk 'BEGIN{srand();}{print rand(), $0}' | sort -n | cut -d' ' -f2- | head -n 500 | cut -f1 | slow5tools get HCV_IVT_002_REP1_ALIGNED_SIGNALS.blow5  -o /content/drive/MyDrive/Single\ Molecular\ Sequencing/HW\ 3/randomly_split_slow5/HCV_IVT_002_REP1_ALIGNED_SIGNALS_subset1.slow5 `

**Comment by Theo-Nelson** [comment]
Hi Nicholas, 

Thanks for letting us know. Glad that it worked today. slow5tools view likely takes longer because it relies on a blow5->slow5 conversion.
